[tool.poetry]
name = "Danger Noodle"
version = "1.0.0"
description = "A simple Battlesnake written in Python"
authors = ["Lawrence Zhang <lawrencezhang04@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
cherrypy = "^18.6"
termcolor = "^1.1.0"
